todo_list/models.py
"""Модели данных для приложения todo_list."""

from datetime import datetime
from sqlalchemy import DateTime, event
from database import db

class Task(db.Model):
    """
    Модель задачи.

    :param id: Идентификатор задачи.
    :type id: int
    :param title: Заголовок задачи.
    :type title: str
    :param description: Описание задачи.
    :type description: str
    :param is_complete: Флаг завершенности задачи.
    :type is_complete: bool
    :param created_at: Дата и время создания задачи.
    :type created_at: datetime
    :param deadline_date: Дата и время крайнего срока выполнения задачи.
    :type deadline_date: datetime, optional
    :param completed_at: Дата и время завершения задачи.
    :type completed_at: datetime, optional
    :param todo_id: Идентификатор списка задач, к которому принадлежит задача.
    :type todo_id: int
    """
    __tablename__ = 'task'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    description = db.Column(db.String(250), nullable=True)
    is_complete = db.Column(db.Boolean, default=False)
    created_at = db.Column(DateTime(timezone=True), default=datetime.now)
    deadline_date = db.Column(DateTime(timezone=True), nullable=True)
    completed_at = db.Column(DateTime(timezone=True), nullable=True)
    todo_id = db.Column(db.Integer, db.ForeignKey('todo_list.id'), nullable=False)

@event.listens_for(Task, 'before_update')
def update_timestamp(mapper, connection, target):
    """
    Обновляет временную метку при завершении задачи.

    :param mapper: Mapper.
    :type mapper: Mapper
    :param connection: Соединение с базой данных.
    :type connection: Connection
    :param target: Экземпляр задачи.
    :type target: Task
    """
    if target.is_complete and not target.completed_at:
        target.completed_at = datetime.now()
    else:
        target.completed_at = None

class TodoList(db.Model):
    """
    Модель списка задач.

    :param id: Идентификатор списка задач.
    :type id: int
    :param title: Заголовок списка задач.
    :type title: str
    :param user_id: Идентификатор пользователя, которому принадлежит список задач.
    :type user_id: int
    :param tasks: Список задач, принадлежащих данному списку задач.
    :type tasks: RelationshipProperty
    """
    __tablename__ = 'todo_list'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    tasks = db.relationship('Task', backref='todo_list', lazy=True, cascade='all, delete-orphan')

todo_list/forms.py
"""Формы для приложения todo_list."""

from datetime import datetime
from pydantic import BaseModel
from typing import List, Union

class TodoCreateForm(BaseModel):
    """
    Форма создания нового списка задач.

    :param title: Заголовок списка задач.
    :type title: str
    """
    title: str

class TodoListForm(TodoCreateForm):
    """
    Форма списка задач.

    :param id: Идентификатор списка задач.
    :type id: int
    :param tasks: Список задач в рамках списка задач.
    :type tasks: List[Union["Task", None]]
    """
    id: int
    tasks: List[Union["Task", None]] = []

class TaskBaseForm(BaseModel):
    """
    Базовая форма для задачи.

    :param title: Заголовок задачи.
    :type title: str
    :param description: Описание задачи.
    :type description: str, optional
    """
    title: str
    description: str = None

class TaskForm(TaskBaseForm):
    """
    Форма задачи.

    :param id: Идентификатор задачи.
    :type id: int
    :param is_complete: Флаг завершенности задачи.
    :type is_complete: bool
    :param todo_list_id: Идентификатор списка задач, к которому принадлежит задача.
    :type todo_list_id: int
    """
    id: int
    is_complete: bool
    todo_list_id: int

class TaskUpdateForm(TaskBaseForm):
    """
    Форма обновления задачи.

    :param id: Идентификатор задачи.
    :type id: int
    """
    id: int

class TaskCreateForm(TaskBaseForm):
    """
    Форма создания новой задачи.

    :param deadline_date: Дата и время крайнего срока выполнения задачи.
    :type deadline_date: datetime, optional
    :param todo_id: Идентификатор списка задач, к которому принадлежит задача.
    :type todo_id: int
    """
    deadline_date: datetime = None
    todo_id: int

todo_list/routes.py
"""Маршруты для приложения todo_list."""

from flask import Blueprint, render_template, request, redirect, url_for, abort, flash
from flask_login import current_user, login_required
from todo_list.services import TaskService, TodoService
from todo_list.forms import TaskCreateForm, TaskUpdateForm, TodoCreateForm

todo_list_bp = Blueprint('todo_list', __name__, url_prefix='/todo_list')


@todo_list_bp.errorhandler(404)
def page_not_found(e):
    """
    Обработчик ошибки 404 (страница не найдена).

    :param e: Исключение.
    :type e: Exception
    """
    flash('Страница не найдена.', 'error')
    return redirect(url_for('todo_list.index'))


@todo_list_bp.errorhandler(403)
def forbidden(e):
    """
    Обработчик ошибки 403 (доступ запрещен).

    :param e: Исключение.
    :type e: Exception
    """
    flash('Доступ запрещен.', 'error')
    return redirect(url_for('todo_list.index'))


@todo_list_bp.get('/')
@login_required
def index():
    """
    Отображает список всех списков задач.

    :return: HTML-страница со списками задач.
    :rtype: flask.Response
    """
    todo_lists = TodoService.get_all_todo(current_user.id)
    return render_template('todo_list/index.html', todo_lists=todo_lists, title='Ваши списки задач')


@todo_list_bp.route('/add', methods=['POST'])
def todo_add():
    """
    Добавляет новый список задач.

    :return: HTML-страница с обновленным списком задач или форма для создания нового списка.
    :rtype: flask.Response
    """
    form_data = request.form
    form = TodoCreateForm(**form_data)
    if form.model_validate(form):
        TodoService.create_todo(**form.model_dump(), user_id=current_user.id)
        return redirect(url_for('todo_list.index'))
    return render_template('todo_list.index.html')


@todo_list_bp.route('/update/<int:todo_id>', methods=['POST'])
def todo_update(todo_id):
    """
    Обновляет заголовок списка задач.

    :param todo_id: Идентификатор списка задач.
    :type todo_id: int
    :return: Редирект на главную страницу со списками задач.
    :rtype: flask.Response
    """
    form_data = request.form
    form = TodoCreateForm(**form_data)
    if form.model_validate(form):
        TodoService.update_todo(todo_id, form.title)
    return redirect(url_for('todo_list.index'))


@todo_list_bp.route('/delete/<int:todo_id>', methods=['POST'])
def todo_delete(todo_id):
    """
    Удаляет список задач.

    :param todo_id: Идентификатор списка задач.
    :type todo_id: int
    :return: Редирект на главную страницу со списками задач.
    :rtype: flask.Response
    """
    TodoService.delete_todo(todo_id)
    return redirect(url_for('todo_list.index'))


@todo_list_bp.get('/<int:todo_id>')
def get_todo(todo_id):
    """
    Отображает список задач по его идентификатору.

    :param todo_id: Идентификатор списка задач.
    :type todo_id: int
    :return: HTML-страница со списком задач.
    :rtype: flask.Response
    """
    todo_list = TodoService.get_todo(todo_id)
    if current_user.id != todo_list.user_id:
        abort(403)
    all_tasks, active_tasks, completed_tasks = TodoService.count_tasks(todo_id)
    context = {
        'title': 'Мои задачи',
        'todo_list': todo_list,
        'active_tasks': active_tasks,
        'completed_tasks': completed_tasks,
        'all_tasks': all_tasks
    }
    return render_template('todo_list/todo_list.html', **context)


@todo_list_bp.route('/<int:todo_id>/task-add', methods=['POST'])
def task_add(todo_id):
    """
    Добавляет новую задачу в список задач.

    :param todo_id: Идентификатор списка задач.
    :type todo_id: int
    :return: Редирект на страницу списка задач.
    :rtype: flask.Response
    """
    form_data = request.form
    form = TaskCreateForm(**form_data, todo_id=todo_id)
    if form.model_validate(form):
        TaskService.add_task(form.title, form.description, form.deadline_date, todo_id)
        return redirect(url_for('todo_list.get_todo', todo_id=todo_id))
    return render_template('todo_list/todo_list.html', form=form)


@todo_list_bp.route('/<int:todo_id>/task-update', methods=['POST'])
def task_update(todo_id):
    """
    Обновляет информацию о задаче.

    :param todo_id: Идентификатор списка задач.
    :type todo_id: int
    :return: Редирект на страницу списка задач.
    :rtype: flask.Response
    """
    form_data = request.form
    form = TaskUpdateForm(**form_data)
    if form.model_validate(form):
        TaskService.update_task(form.id, form.title, form.description)
    return redirect(url_for('todo_list.get_todo', todo_id=todo_id))


@todo_list_bp.route('/<int:todo_id>/task-completed', methods=['POST'])
def task_completed(todo_id):
    """
    Помечает задачу как завершенную.

    :param todo_id: Идентификатор списка задач.
    :type todo_id: int
    :return: Редирект на страницу списка задач.
    :rtype: flask.Response
    """
    task_id = request.form.get('task_id')
    TaskService.complete_task(task_id)
    return redirect(url_for('todo_list.get_todo', todo_id=todo_id))


@todo_list_bp.route('/<int:todo_id>/task-delete', methods=['POST'])
def task_delete(todo_id):
    """
    Удаляет задачу из списка задач.

    :param todo_id: Идентификатор списка задач.
    :type todo_id: int
    :return: Редирект на страницу списка задач.
    :rtype: flask.Response
    """
    task_id = request.form.get('task_id')
    TaskService.delete_task(task_id)
    return redirect(url_for('todo_list.get_todo', todo_id=todo_id))

templates/todo_list/index.html
{% extends "base.html" %}
{% block title %}Главная{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-4 mb-4">Списки задач</h1>
    {% if todo_lists %}
    <div class="card-container">
        {% for todo_list in todo_lists %}
        <div class="card">
            <div class="card-body">
                <a href="{{ url_for('todo_list.get_todo', todo_id=todo_list.id) }}" style="text-decoration: none; color: inherit;">
                    <h5 class="card-title">{{ todo_list.title }}</h5>
                </a>                
                <div class="card-buttons">
                    <button class="btn btn-info edit-button" data-todo-id="{{ todo_list.id }}">Редактировать</button>
                    <form action="{{ url_for('todo_list.todo_delete', todo_id=todo_list.id) }}" method="post">
                        <button class="btn btn-danger delete-button" type="submit">Удалить</button>
                    </form>
                </div>
            </div>
            <div class="update-form" id="update-form-{{ todo_list.id }}" style="display: none;">
                <form class="form-inline" action="{{ url_for('todo_list.todo_update', todo_id=todo_list.id) }}" method="post">
                    <div class="form-group mb-2 text-center">
                        <input type="text" class="form-control" name="title" placeholder="Введите новое название" required>
                    </div>
                    <button type="submit" class="btn btn-info mb-2 ml-2">Обновить</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h2>Пока нет ни одного списка задач.</h2>
    {% endif %}
</div>

<div class="container mt-4">
    <h2>
        <button class="btn btn-success" id="create-todo-btn">Создать новый список задач</button>
    </h2>
    <form id="create-todo-form" action="{{ url_for('todo_list.todo_add') }}" method="post" style="display: none;">
        <div class="form-group text-center">
            <input type="text" class="form-control" name="title" placeholder="Введите название" style="width: 50%; margin: 0 auto;">
        </div>
        <button type="submit" class="btn btn-success">Добавить</button>
    </form>
</div>
{% endblock %}

templates/todo_list/todo_list.html
{% extends "base.html" %}
{% block title %}Мои задачи{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Задачи в списке "{{ todo_list.title }}"</h1>
    <p>Всего задач: {{ all_tasks }}</p>
    <p>Активные задачи: {{ active_tasks }}</p>
    <p>Завершенные задачи: {{ completed_tasks }}</p>
    {% if todo_list.tasks %}
    <div class="card-container">
        {% for task in todo_list.tasks %}
        <div class="card mt-4">
            <div class="card-body">
                <h5 class="card-title">{{ task.title }}</h5>
                <p class="card-text">{{ task.description }}</p>
                <p class="card-text">Дедлайн: {{ task.deadline_date }}</p>
                {% if task.is_complete %}
                    <span class="badge badge-success">Завершена. Выполнено: {{ task.completed_at }}</span>
                {% else %}
                    <span class="badge badge-secondary">Не завершена</span>
                {% endif %}
                <div class="card-buttons mt-2">
                    <button class="btn btn-info edit-button" data-task-id="{{ task.id }}">Редактировать</button>
                    <form action="{{ url_for('todo_list.task_delete', todo_id=todo_list.id) }}" method="post" style="display: inline;">
                        <input type="hidden" name="task_id" value="{{ task.id }}">
                        <button class="btn btn-danger delete-button" type="submit">Удалить</button>
                    </form>
                    <form action="{{ url_for('todo_list.task_completed', todo_id=todo_list.id) }}" method="post" style="display: inline;">
                        <input type="hidden" name="task_id" value="{{ task.id }}">
                        <button class="btn btn-success complete-button" type="submit">Завершить</button>
                    </form>
                </div>
                <div class="update-form mt-2" id="update-form-{{ task.id }}" style="display: none;">
                    <form class="form-inline" action="{{ url_for('todo_list.task_update', todo_id=todo_list.id, task_id=task.id) }}" method="post">
                        <div class="form-group mr-2">
                            <input type="text" class="form-control" name="title" placeholder="Новое название" value="{{ task.title }}">
                        </div>
                        <div class="form-group mr-2">
                            <input type="text" class="form-control" name="description" placeholder="Новое описание" value="{{ task.description }}">
                        </div>
                        <input type="hidden" name="id" value="{{ task.id }}">
                        <button class="btn btn-primary" type="submit">Обновить</button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>Пока нет ни одной задачи в этом списке.</p>
    {% endif %}
</div>

<div class="container mt-4">
    <h2>Добавить новую задачу:</h2>
    <form action="{{ url_for('todo_list.task_add', todo_id=todo_list.id) }}" method="post">
        <div class="form-group">
            <input type="text" class="form-control" name="title" placeholder="Название">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" name="description" placeholder="Описание">
        </div>
        <div class="form-group">
            <input type="datetime-local" class="form-control" name="deadline_date" placeholder="Дедлайн">
        </div>
        <button type="submit" class="btn btn-success">Добавить</button>
    </form>
</div>

<script>
    const editButtons = document.querySelectorAll('.edit-button');
    editButtons.forEach(button => {
        button.addEventListener('click', () => {
            const taskId = button.getAttribute('data-task-id');
            const updateForm = document.getElementById(`update-form-${taskId}`);
            if (updateForm.style.display === 'none') {
                updateForm.style.display = 'block';
            } else {
                updateForm.style.display = 'none';
            }
        });
    });
</script>
{% endblock %}